chore: fix PHP version for Psalm to 8.1
PHP 7.4 causes UndefinedFunction errors.

Error: src/Auth.php:54:15: MissingDependency: CodeIgniter\Shield\Models\UserModel depends on class or interface codeigniter\basemodel that does not exist (see https://psalm.dev/157)