refactor: replace deprecated Faker property access
ErrorException: Since fakerphp/faker 1.14: Accessing property "userName" is deprecated, use "userName()" instead.